## Zadania

In [2]:
import numpy as np

**Zadanie 1**

Stwórz tablicę numpy o wymiarach (4,4) wypełnioną wartościami od 2 do 32 z krokiem 2 i przypisz ją do zmiennej.
Wyświetl jej typ danch, liczbę elementów, wielkość pojedynczego elementu oraz ilość zaalokowanej pamięci.

In [47]:
A = np.array([
    [2, 4, 6, 8],
    [10, 12, 14, 16],
    [18, 20, 22, 24],
    [26, 28, 30, 32]
])
print(A.dtype, A.size, A.itemsize, (A.itemsize * A.size), A.nbytes)
A.base is None # oryginalna tablica, nie widokiem.

int64 16 8 128 128


True

In [ ]:
#Alternatywy do pierwszego zadania
AA = np.arange(2,33,2).reshape(4,4) #widok
print(AA.base) #wskazuje na oryginalną tablicę, jeśli istnieje, lub None, jeśli tablica jest oryginalna.

AA = np.arange(2,33,2) #oryginalna tablica
AA.shape = (4,4)
print(AA.base) #wskazuje na oryginalną tablicę, jeśli istnieje, lub None, jeśli tablica jest oryginalna.


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32]
None


**Zadanie 2**

Zwróć tablicę z zadania 1 jako widok.
Zmień jej typ danych (możesz to zrobić np. funkcją `astype()`) na np.uint8.
Sprawdź teraz czy tablica jest widokiem czy kopią tablicy oryginalnej. Wyświetl jej liczbę elementów, wielkość pojedynczego elementu oraz ilość zaalokowanej pamięci.

In [48]:
C = A[...]

print("Do:",C.dtype, C.size, C.itemsize, C.nbytes)
print(C.base is A) #True bo C jest widokiem A, a nie kopią.

C = C.astype(np.uint8) #zwraca kopię tablicy z nowym typem danych, a nie widok.

print("Po:", C.dtype, C.size, C.itemsize, C.nbytes)
print(C.base is A) #False, bo C jest teraz kopią A  z nowym typem danych, a nie widokiem.

Do: int64 16 8 128
True
Po: uint8 16 1 16
False


In [24]:
# sposoby tworzenia widoku tablicy A
# nie jestem pewna czy są poprawne/ w stylu numpy
#B = A[:]
#B = A.reshape(4,4)
#B = A[:,:]
#B = A[...,...] #an index can only have a single ellipsis ('...')
#B = A[...,:]
#B = A[...]

**Zadanie 3**

Wytnij z tablicy z zadania 1 obszar 2 x 2 "ze środka" tablicy (wartości 12,14, 20,22) na dwa sposoby:
* jeden jako widok i przypisz do zmiennej
* drugi jako kopia i przypisz do zmiennej
Posługując się przykładami z zajęć sprawdź czy baza tych dwóch tablic jest różna (powinna być).

In [ ]:
print(A,end="\n\n")

B = A[1:3, 1:3]
print("B.base is A:", B.base is A) # True, bo B jest widokiem A, a nie kopią, więc współdzieli pamięć z A.
print(B, end="\n\n")

D =A[1:3, [1,2]]
print("D.base is A:", D.base is A) # False bo D jest kopią, a nie widokiem, więc nie współdzieli pamięci z A.
print(D, end="\n\n")


print("Baza tych dwóch tablic jest różna:")
print("A.base:", A.base) # None, bo A jest oryginalną tablicą, a nie widokiem, więc nie współdzieli pamięci z inną tablicą.
print("D.base:", D.base) # None, bo D jest kopią, a nie widokiem, więc nie współdzieli pamięci z A.
print("B.base:", B.base) 

(D.base is A) and (B.base is A) # False,baza tych dwóch tablic jest różna bo D jest kopią, a nie widokiem, więc nie współdzieli pamięci z A, podczas gdy B jest widokiem A, więc współdzieli pamięć z A.

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

B.base is A: True
[[12 14]
 [20 22]]

D.base is A: False
[[12 14]
 [20 22]]

Baza tych dwóch tablic jest różna:
A.base: None
D.base: [[12 20]
 [14 22]]
B.base: [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


False

**Zadanie 4**

Stwórz tablicę 4x4, która zawiera wartości 1,2,3,4 w każdym wierszu.
Następnie wykorzystując funkcje łączenia tablic utwórz tablicę połączoną z powyższej tablicy i jej wersji lustrzanej w poziomie (spróbuj użyć wycinków). Postać każdego wiersza po połączeniu: `[1 2 3 4 4 3 2 1]`


In [8]:
num = [1,2,3,4]
F = np.array([num for _ in range(4)])
print(F, end="\n\n")
#fun. lączenia tablic
#A to lustarna wersja F

A = F[::-1,::-1]
print(A, end="\n\n")

result = np.concatenate((F,A), axis=1)
print(result, end="\n\n")



[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

[[4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]]

[[1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]]



**Zadanie 5**

Utwórz tablicę o nazwie `Z_5` o wymiarach 2x2 wypełnioną wartościami 1.
Wykorzystując funkcje łączenia tabel uwtórz tablicę, która finalnie będzie tablicą składającą się z 4-ech tablic `Z_5`, ale tak aby finalnie była to tablica 4 x 4 podobna do poniższej:

1,1,2,2  
1,1,2,2  
3,3,4,4  
3,3,4,4  

In [ ]:
Z_5 = np.ones((2,2), dtype=np.int32)
print(Z_5, end="\n\n")

# Tworzenie 4 bloków
Z_4 = Z_5[[0,1]]
Z_4[:] = 2
print(Z_4, end="\n\n")

Z_3 = Z_5[[0,1]]
Z_3[:] = 3
print(Z_3, end="\n\n")

Z_2 = Z_5[[0,1]]
Z_2[:] = 4
print(Z_2, end="\n\n")

part1 = np.concatenate((Z_5,Z_4), axis=1)
print(part1, end="\n\n")

part2 = np.concatenate((Z_3,Z_2), axis=1)
print(part1, end="\n\n")

final = np.concatenate((part1,part2), axis=0)
print(final, end="\n\n")


[[1 1]
 [1 1]]

[[2 2]
 [2 2]]

[[3 3]
 [3 3]]

[[4 4]
 [4 4]]

[[1 1 2 2]
 [1 1 2 2]]

[[1 1 2 2]
 [1 1 2 2]]

[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]

[[1 1]
 [1 1]]



In [34]:

Z_5 = np.ones((2, 2), dtype=int)

# Tworzenie 4 bloków
A = Z_5 * 1
B = Z_5 * 2
C = Z_5 * 3
D = Z_5 * 4

part1 = np.hstack((A,B))
print(part1, end="\n\n")

part2 = np.hstack((C,D))
print(part2, end="\n\n")

final = np.vstack((part1,part2))
print(final)

[[1 1 2 2]
 [1 1 2 2]]

[[3 3 4 4]
 [3 3 4 4]]

[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]
