In [1]:
import numpy as np

1. Stwórz tablicę o nazwie a_small_one o wymiarach 8x8 z wartościami od 1 do 64.

In [9]:
a_small_one = np.arange(1,65).reshape(8,8)
print(a_small_one)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


2. Dla tablicy a_small_one policz:

- sumę dla każdej kolumny,
- sumę skumulowaną dla każdego wiersza,
- wartość średnią dla każdego wiersza,

In [11]:
#1
sum_kol = a_small_one.sum(axis=0)
print(sum_kol, '\n')

#2
sum_skum = a_small_one.cumsum(axis=1)
print(sum_skum, '\n')

row_mean =  a_small_one.mean(axis=1)
print(row_mean, '\n')

[232 240 248 256 264 272 280 288] 

[[  1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100]
 [ 17  35  54  74  95 117 140 164]
 [ 25  51  78 106 135 165 196 228]
 [ 33  67 102 138 175 213 252 292]
 [ 41  83 126 170 215 261 308 356]
 [ 49  99 150 202 255 309 364 420]
 [ 57 115 174 234 295 357 420 484]] 

[ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5] 



3. Zwróć podtablicę z tablicy a_small_one z elementami parzystymi (nie nadpisuj tej zmiennej).


In [13]:
a_small_one % 2 == 0

array([[False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True]])

In [12]:
par_small_one = a_small_one[a_small_one % 2 == 0]
print(par_small_one)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


4. Zapisz do zmiennej o nazwie no_even_small_one tablicę a_small_one zamieniając wartości parzyste na wartość np.nan.

In [28]:
no_even_small_one = a_small_one.copy().astype(float)
no_even_small_one[no_even_small_one % 2 == 0] = np.nan
print(no_even_small_one)

[[ 1. nan  3. nan  5. nan  7. nan]
 [ 9. nan 11. nan 13. nan 15. nan]
 [17. nan 19. nan 21. nan 23. nan]
 [25. nan 27. nan 29. nan 31. nan]
 [33. nan 35. nan 37. nan 39. nan]
 [41. nan 43. nan 45. nan 47. nan]
 [49. nan 51. nan 53. nan 55. nan]
 [57. nan 59. nan 61. nan 63. nan]]


5. Dla tablicy no_even_small_one policz funkcjami uwzględniającymi wartości nan (zazwyczaj posiadają przedrostek nan):

- sumę dla każdego wiersza,
- średnią dla każdej kolumny,
- wartość najmniejszą w całej tablicy,

In [29]:
#1
sum_row = np.nansum(no_even_small_one,axis=1)
print(sum_row)

#2
col_mean = np.nanmean(no_even_small_one, axis=0)
print(col_mean)

#3
min_val = np.nanmin(no_even_small_one)
print(min_val)


[ 16.  48.  80. 112. 144. 176. 208. 240.]
[29. nan 31. nan 33. nan 35. nan]
1.0


C:\Users\User\AppData\Local\Temp\ipykernel_1628\3655283933.py:6: RuntimeWarning: Mean of empty slice
  col_mean = np.nanmean(no_even_small_one, axis=0)


6. Do tablicy no_even_small_one wstaw za pomocą funkcji np.where:

- wartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję np.isnan())

- liczby parzyste, które wcześniej zastąpiliśmy wartościami nan (teraz 1 jeżeli wykonany jest podpunkt pierwszy), więc przywracamy ten tablicy wygląd oryginalny z tablicy a_small_one - dla warunku wstawiaj wartość z a_small_one lub no_even_small_one


In [33]:
# warunek = np.where(np.isnan(no_even_small_one))
# no_even_small_one[warunek] = 1
# print(no_even_small_one)

no_even_small_one = np.where(np.isnan(no_even_small_one), 1, no_even_small_one)
print(no_even_small_one, '\n')

no_even_small_one = np.where(a_small_one % 2 == 0, a_small_one, no_even_small_one)
print(no_even_small_one)



[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]] 

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]


7. Stwórz tablicę o nazwie sto_by_sto o wymiarach 100x100 próbkując wartości z rozkładu normalnego standardowego.

In [34]:
rng = np.random.default_rng()
sto_by_sto = rng.normal(size=(100,100))
print(sto_by_sto)


[[ 0.28582835 -1.33181305 -1.36382381 ... -1.27430773  0.28212899
  -0.50215976]
 [ 0.99269311 -0.11003333  0.83250667 ... -2.47978433  0.35860198
   0.55864622]
 [-1.10009888 -0.94079925  0.37162108 ...  0.42295334 -0.11306688
  -0.4828316 ]
 ...
 [ 0.29095638  0.18538645 -0.96194719 ...  1.36452983 -0.1669075
  -0.47062587]
 [-0.1359364   0.67713958  0.29331851 ... -1.26484724  0.03038674
  -1.25833254]
 [ 1.33891376  0.66834244 -0.53632999 ...  1.77806631  0.94444649
  -0.09018501]]


8. Dla tablicy sto_by_sto policz:

- wartość średnią w każdym wierszu i kolumnie (oddzielnie),

- policz średnią różnicę bezwzględną dla wartości w powyższym punkcie względem wartości 0 (to jest wartość oczekiwana przy naszych założeniach rozkładu normalnego) 

- oddzielnie dla średniej z kolumn i średniej z wierszy, pamiętam o tym, że operacje na tablicy numpy wykonywane są w trybie broadcast.

In [37]:
#wartość średnią w każdym wierszu
row_mean = sto_by_sto.mean(axis=1)
#print(row_mean)

#wartość średnią w każdej kolumnie
kol_mean = sto_by_sto.mean(axis=0)
#print(kol_mean)

#abs(x - 0) = abs(x)
#abs_sto_by_sto = np.abs(sto_by_sto)


abs_col_mean = np.mean(np.abs(sto_by_sto), axis=0)

abs_row_mean = np.mean(np.abs(sto_by_sto), axis=1)
print(abs_row_mean)

[0.88973581 0.85101067 0.88105853 0.84264597 0.75754861 0.83632821
 0.92894059 0.75543418 0.77715541 0.79376012 0.76904975 0.77085149
 0.84306784 0.78560848 0.81881123 0.79685522 0.75694111 0.79166229
 0.83304419 0.75912984 0.74523013 0.78616131 0.87370729 0.84496918
 0.783373   0.70027903 0.887902   0.87443387 0.79390193 0.90571689
 0.94832367 0.83206615 0.72785339 0.79282401 0.94854655 0.85434579
 0.70222591 0.67379716 0.75326554 0.86992879 0.81227691 0.77191771
 0.75496002 0.83274826 0.8198735  0.80866965 0.68518536 0.76071634
 0.82057302 0.82613013 0.80836811 0.83778081 0.81119409 0.74996006
 0.78402342 0.75463032 0.72011195 0.77521009 0.77626284 0.72799947
 0.8566164  0.76917353 0.80330023 0.75883659 0.75983885 0.82033522
 0.776777   0.79250319 0.81616432 0.73841027 0.80016504 0.87493988
 0.77390278 0.87481435 0.82880774 0.73431036 0.76661794 0.72133268
 0.80156258 0.7847877  0.79639335 0.71877889 0.75255639 0.82044652
 0.75364426 0.85537358 0.83216395 0.77567421 0.73658427 0.7543

9. Stwórz tablicę o wymiarach 1000x1000 uzupełniając ją wartościami losowymi z rozkładu normalnego standardowego, a następnie posiłkując się przykładami z labów poprzednich (moduł timeit) porównaj czasy wykonania dla tej tablicy:

- zapisu do pliku tekstowego vs. zapis do pliku w formacie picle vs. zapis do pliku skompresowanego (funkcja savez_compressed w dokumentacji biblioteki numpy)
- odczytu dla trzech wyżej wymienionych plików.

In [45]:
from timeit import timeit
import numpy as np

stmt3 = "np.savetxt('sto_by_sto.txt', sto_by_sto)"
stmt4 = "np.save('arr_pickle.npy', sto_by_sto)"
stmt5 = "np.savez_compressed('arr_compressed.npz', arr = sto_by_sto)"

stmt6 = "np.loadtxt('sto_by_sto.txt')"
stmt7 = "np.load('arr_pickle.npy')"
stmt8 = "np.load('arr_compressed.npz', allow_pickle=True)['arr']"

setup = """
import numpy as np
rng = np.random.default_rng()
sto_by_sto = rng.normal(size=(1000,1000))
"""

t3 = timeit(stmt=stmt3, setup=setup, number=10)
t4 = timeit(stmt=stmt4, setup=setup, number=10)
t5 = timeit(stmt=stmt5, setup=setup, number=10)

t6 = timeit(stmt=stmt6, setup=setup, number=10)
t7 = timeit(stmt=stmt7, setup=setup, number=10)
t8 = timeit(stmt=stmt8, setup=setup, number=10)


print("Zapis do txt:", t3)
print("Zapis do npy:", t4)
print("Zapis do npz:", t5)

print("Odczyt z txt:", t6)
print("Odczyt z npy:", t7)
print("Odczyt z npz:", t8)

Zapis do txt: 11.475677299997187
Zapis do npy: 0.04190389999712352
Zapis do npz: 4.7479514999868115
Odczyt z txt: 7.020444900001166
Odczyt z npy: 0.06881630000134464
Odczyt z npz: 0.7995183000020916
